// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnbxsemhjiatjtwisywz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduYnhzZW1oamlhdGp0d2lzeXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MzAxNTksImV4cCI6MjA1MTMwNjE1OX0.coXrD49Rl3U6xVku_ajgOQ3HkQCxlbGStLYvQM7AGzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);